blank_issues_enabled: true
contact_links:
    - name: Discord Server
      url: https://discord.com/invite/dECQZNNngD
      about: Please use our Discord for questions, help or feature requests. Issues should be used for bug reports.
