name: Create Modpack Release

on:
    workflow_dispatch:
        inputs:
            ref:
                description: "Mierno repository reference (branch/tag)"
                default: "main"
                required: true

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
                  ref: ${{ github.event.inputs.ref }}

            - name: Set up environment and determine version
              id: setup
              run: |
                  # 打印仓库结构以进行调试
                  echo "Debugging repository structure:"
                  ls -R || { echo "Failed to list repository structure"; exit 1; }

                  # 检查 CHANGELOG.md 是否存在
                  CHANGELOG_PATH="./CHANGELOG.md"
                  if [ ! -f "$CHANGELOG_PATH" ]; then
                      echo "Error: $CHANGELOG_PATH not found in repository root."
                      exit 1
                  fi

                  # 打印 CHANGELOG.md 内容以进行调试
                  echo "Debugging CHANGELOG.md content:"
                  cat "$CHANGELOG_PATH" || { echo "Failed to read $CHANGELOG_PATH"; exit 1; }

                  # 从 CHANGELOG.md 中提取最新版本号
                  LATEST_VERSION=$(grep -oP '^## v\K[0-9]+(\.[0-9]+)*' "$CHANGELOG_PATH" | head -n1)

                  if [ -z "$LATEST_VERSION" ]; then
                      echo "Error: Failed to extract version from $CHANGELOG_PATH. Ensure it contains a line starting with '## v' followed by a version number."
                      exit 1
                  fi

                  echo "Extracted version: $LATEST_VERSION"
                  echo "VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
                  echo "ZIP_NAME=Mierno-$LATEST_VERSION.zip" >> $GITHUB_OUTPUT
                  echo "SERVER_ZIP_NAME=Mierno-$LATEST_VERSION-server.zip" >> $GITHUB_OUTPUT

            - name: Debug outputs
              run: |
                  echo "VERSION is ${{ steps.setup.outputs.VERSION }}"
                  echo "ZIP_NAME is ${{ steps.setup.outputs.ZIP_NAME }}"
                  echo "SERVER_ZIP_NAME is ${{ steps.setup.outputs.SERVER_ZIP_NAME }}"

            - name: Update manifest.json version
              run: |
                  sed -i '/"name": *"Mierno",/!b;n;s/"version": *"[^"]*"/"version": "${{ steps.setup.outputs.VERSION }}"/' manifest.json
                  echo "Updated manifest.json with version ${{ steps.setup.outputs.VERSION }}"

            - name: Create and package modpack
              run: |
                  mkdir overrides
                  cp -r config defaultconfigs hotai kubejs ldlib overrides/
                  zip -r ${{ steps.setup.outputs.ZIP_NAME }} overrides manifest.json modlist.html

            - name: Create and package server pack
              run: |
                  # 创建服务端打包目录
                  mkdir server_pack

                  # 复制必要的目录到服务端打包目录
                  cp -r config defaultconfigs kubejs ldlib server_pack/

                  # 进入服务端打包目录
                  cd server_pack

                  # 根据 server_pack 的 .gitignore 删除客户端相关文件
                  rm -rf config/jade
                  rm -rf config/modpack-update-checker
                  rm -rf config/ProjectE/client.toml
                  rm -rf config/ars_nouveau-client.toml
                  rm -rf config/botania-client.toml
                  rm -rf config/embeddium++.toml
                  rm -rf config/fluffy_fur-client.toml
                  rm -rf config/invtweaks-client.toml
                  rm -rf config/occultism-client.toml
                  rm -rf config/patchouli-client.toml

                  rm -rf defaultconfigs/ftbchunks/client-config.snbt
                  rm -rf defaultconfigs/ftbquests/client-config.snbt

                  rm -rf kubejs/startup_scripts/client

                  # 删除 hotai
                  rm -rf hotai

                  # 返回根目录
                  cd ..

                  # 复制服务端特有文件到服务端打包目录
                  # 假设服务端文件位于 server_files/ 目录下，请根据实际情况调整
                  cp -r server_files/* server_pack/

                  # 确保不包含 README.md 和 .gitignore
                  rm -f server_pack/README.md server_pack/.gitignore

                  # 打包服务端
                  zip -r ${{ steps.setup.outputs.SERVER_ZIP_NAME }} server_pack

            - name: Extract CHANGELOG for current version
              run: |
                  sed -n "/^## v${{ steps.setup.outputs.VERSION }}/,/^## /p" CHANGELOG.md | sed '$d' > extracted_changelog.txt

            - name: Create GitHub Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create "v${{ steps.setup.outputs.VERSION }}" \
                    ${{ steps.setup.outputs.ZIP_NAME }} \
                    ${{ steps.setup.outputs.SERVER_ZIP_NAME }} \
                    --title "Mierno v${{ steps.setup.outputs.VERSION }}" \
                    --notes-file extracted_changelog.txt

            - name: Additional Debugging
              run: |
                  echo "Final extracted changelog:"
                  cat extracted_changelog.txt
