name: Publish to CurseForge

on:
    workflow_dispatch:
        inputs:
            release_tag:
                description: "GitHub Release tag"
                required: true
            version_type:
                description: "CurseForge release type"
                required: true
                type: choice
                default: "beta"
                options:
                    - "release"
                    - "beta"
                    - "alpha"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main branch
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
                  ref: main
                  path: main_repo

            - name: Extract version and changelog
              id: changelog
              run: |
                  cd main_repo

                  CHANGELOG_PATH="./CHANGELOG.md"
                  if [ ! -f "$CHANGELOG_PATH" ]; then
                    echo "Error: $CHANGELOG_PATH not found."
                    exit 1
                  fi

                  LATEST_VERSION=$(grep -oP '^## v\K[0-9]+(\.[0-9]+)*' "$CHANGELOG_PATH" | head -n 1)
                  if [ -z "$LATEST_VERSION" ]; then
                    echo "Error: Failed to extract version from $CHANGELOG_PATH. Make sure it has a line like '## v0.1.5'"
                    exit 1
                  fi

                  echo "Latest version from CHANGELOG: $LATEST_VERSION"

                  sed -n "/^## v${LATEST_VERSION}/,/^## /p" "$CHANGELOG_PATH" | sed '$d' > ../extracted_changelog.txt

                  echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

            - name: Download release artifacts
              run: |
                  cd $GITHUB_WORKSPACE
                  TAG="${{ github.event.inputs.release_tag }}"
                  VERSION="${{ steps.changelog.outputs.version }}"

                  curl -L "https://github.com/FalAut/Mierno/releases/download/${TAG}/Mierno-${VERSION}.zip" \
                    -o "Mierno-${VERSION}.zip"
                  curl -L "https://github.com/FalAut/Mierno/releases/download/${TAG}/Mierno-${VERSION}-server.zip" \
                    -o "Mierno-${VERSION}-server.zip"

            - name: Publish to CurseForge
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  curseforge-id: "1167719"

                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

                  files: |
                      Mierno-${{ steps.changelog.outputs.version }}.zip
                      Mierno-${{ steps.changelog.outputs.version }}-server.zip

                  version: ${{ steps.changelog.outputs.version }}

                  version-type: ${{ github.event.inputs.version_type }}

                  name: Mierno-${{ steps.changelog.outputs.version }}.zip

                  loaders: forge

                  game-versions: 1.20.1

                  changelog-file: extracted_changelog.txt
