name: Sync main to server_pack

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
              with:
                  ref: main

            - name: Set Git User
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Checkout server_pack branch
              run: |
                  git fetch origin server_pack
                  git checkout server_pack

            - name: Sync white-listed files
              run: |
                  # 获取白名单文件
                  git ls-tree -r --name-only HEAD > file_list.txt

                  # 排除 .gitignore 和 README.md
                  grep -vE '^(.gitignore|README.md)$' file_list.txt > filtered_file_list.txt

                  # 使用 rsync 同步文件
                  rsync -av --files-from=filtered_file_list.txt ./ ./

            - name: Commit and Push changes
              run: |
                  if ! git diff-index --quiet HEAD; then
                      git add .
                      git commit -m "Sync server_pack from main"
                      git push origin server_pack
                  else
                      echo "No changes to commit."
                  fi
