name: Rebuild server_pack branch

on:
    push:
        branches:
            - main

jobs:
    rebuild:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3

            - name: Set Git User
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Rebuild server_pack branch
              run: |
                  git checkout --orphan server_pack
                  git reset --hard
                  git clean -fdx

                  git checkout main -- .

                  git checkout server_pack .gitignore

                  git status --ignored --short | grep '^!! ' | awk '{print $2}' | xargs -I{} rm -rf {}

                  git add .
                  git commit -m "Rebuild server_pack branch from main"
                  git push origin server_pack --force
